name: Daily Sleep-Relaxation Video

on:
  schedule:
    - cron: '0 3 * * *'       # Runs daily at 03:00 UTC
  workflow_dispatch:         # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Install system packages needed by MoviePy
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # 2. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # 5. Generate the 8-hour sleep video
      - name: Generate video
        run: python make_video.py

      # 6. Generate metadata for YouTube
      - name: Generate metadata
        run: python generate_meta.py

      # 7. Create a thumbnail
      - name: Create thumbnail
        run: bash make_thumbnail.sh

      # 8. Prepare YouTube OAuth files from secrets
      - name: Prepare YouTube credentials
        run: |
          echo "${{ secrets.YT_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.YT_TOKEN }}"      > token.json

      # 9. Upload to YouTube and capture the new video ID
      - name: Upload to YouTube
        id: upload
        run: |
          VIDEO_ID=$(python upload.py)
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      # 10. Tweet the new video link
      - name: Tweet video link
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN:  ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LAST_VIDEO_ID:         ${{ steps.upload.outputs.video_id }}
        run: python post_twitter.py
