name: Daily Sleep-Relaxation Video

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install FFmpeg
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # 3. Set up Python 3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Install & verify MoviePy using python3 -m pip
      - name: Install, verify, and generate video
        run: |
          # Use python3 explicitly
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install moviepy imageio-ffmpeg openai \
                                 google-auth-oauthlib google-api-python-client \
                                 tweepy python-dotenv

          # Verify with python3
          python3 -c "import moviepy.editor; print('✅ MoviePy version:', moviepy.editor.__version__)"

          # Generate the video
          python3 make_video.py

      # 5. Generate metadata
      - name: Generate metadata
        run: python3 generate_meta.py

      # 6. Create thumbnail
      - name: Create thumbnail
        run: bash make_thumbnail.sh

      # 7. Prepare YouTube credentials
      - name: Prepare YouTube credentials
        run: |
          echo "${{ secrets.YT_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.YT_TOKEN }}"      > token.json

      # 8. Upload to YouTube
      - name: Upload to YouTube
        id: upload
        run: |
          VIDEO_ID=$(python3 upload.py)
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      # 9. Tweet video link
      - name: Tweet video link
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN:  ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LAST_VIDEO_ID:         ${{ steps.upload.outputs.video_id }}
        run: python3 post_twitter.py
