name: Daily Sleep-Relaxation Video

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code (this puts it in workspace/sleep-relax-yt)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install ffmpeg system package
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # 3) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Install Python dependencies inside the inner folder
      - name: Install Python dependencies
        working-directory: sleep-relax-yt
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # 5) Generate the video
      - name: Generate video
        working-directory: sleep-relax-yt
        run: python make_video.py

      # 6) Generate metadata
      - name: Generate metadata
        working-directory: sleep-relax-yt
        run: python generate_meta.py

      # 7) Create the thumbnail
      - name: Create thumbnail
        working-directory: sleep-relax-yt
        run: bash make_thumbnail.sh

      # 8) Prepare YouTube credentials
      - name: Prepare YouTube credentials
        working-directory: sleep-relax-yt
        run: |
          echo "${{ secrets.YT_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.YT_TOKEN }}"      > token.json

      # 9) Upload to YouTube
      - name: Upload to YouTube
        id: upload
        working-directory: sleep-relax-yt
        run: |
          VIDEO_ID=$(python upload.py)
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      # 10) Tweet the video link
      - name: Tweet video link
        working-directory: sleep-relax-yt
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN:  ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LAST_VIDEO_ID:         ${{ steps.upload.outputs.video_id }}
        run: python post_twitter.py
