name: Daily Sleep-Relaxation Video

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Generate video
        run: python make_video.py

      - name: Generate metadata
        run: python generate_meta.py

      - name: Create thumbnail
        run: bash make_thumbnail.sh

      - name: Prepare YouTube credentials
        run: |
          echo "${{ secrets.YT_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.YT_TOKEN }}"      > token.json

      - name: Upload to YouTube
        id: upload
        run: |
          VIDEO_ID=$(python upload.py)
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      - name: Tweet video link
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN:  ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LAST_VIDEO_ID:         ${{ steps.upload.outputs.video_id }}
        run: python post_twitter.py
