name: Daily Sleep-Relaxation Video

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Force-reinstall to ensure presence
          pip install --force-reinstall moviepy imageio-ffmpeg openai \
                                 google-auth-oauthlib google-api-python-client \
                                 tweepy python-dotenv

      - name: Debug installed packages
        run: |
          echo "Python at: $(which python)"
          pip show moviepy || echo "moviepy not found"
          pip show imageio-ffmpeg || echo "imageio-ffmpeg not found"
          pip list

      - name: Generate video
        run: python make_video.py

      - name: Generate metadata
        run: python generate_meta.py

      - name: Create thumbnail
        run: bash make_thumbnail.sh

      - name: Prepare YouTube credentials
        run: |
          echo "${{ secrets.YT_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.YT_TOKEN }}"      > token.json

      - name: Upload to YouTube
        id: upload
        run: |
          VIDEO_ID=$(python upload.py)
          echo "video_id=$VIDEO_ID" >> $GITHUB_OUTPUT

      - name: Tweet video link
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN:  ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LAST_VIDEO_ID:         ${{ steps.upload.outputs.video_id }}
        run: python post_twitter.py
